name: publish

on: push

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete old files for 1.16
        run: 'rm 1.16/default-116.zip'

      - name: Delete old files for 1.17
        run: 'rm 1.17/default-117.zip'

      - name: Compress 1.16 files
        # You may pin to the exact commit or the version.
        # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip
          files: '1.16/default-116/'
          # Name of output zip file
          dest: '1.16/default-116.zip'
          # Whether to add subdirectories to simply zip all files to the root
          recursive: true

      - name: Compress 1.17 files
        # You may pin to the exact commit or the version.
        # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip
          files: '1.17/default-117'
          # Name of output zip file
          dest: '1.17/default-117.zip'
          # Whether to add subdirectories to simply zip all files to the root
          recursive: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: 'Release'
          name: 'Release'
          allowUpdates: true
          artifacts: 1.16/default-116.zip, 1.17/default-117.zip
          bodyFile: 'changelog.md'
          token: ${{ secrets.GITHUB_TOKEN }}
