name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update'
        default: 'default-117'
        required: true
      exact_version:
        description: 'Exact version number'
        default: '1.17'
        required: true

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: delete old files
        run: rm ${{ github.event.inputs.exact_version }}/${{ github.event.inputs.version }}.zip


      - name: Compress files
        # You may pin to the exact commit or the version.
        # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        uses: vimtor/action-zip@v1
        with:
          # Files or directories to zip
          files: '${{ github.event.inputs.exact_version }}/${{ github.event.inputs.version }}/'
          # Name of output zip file
          dest: '${{ github.event.inputs.exact_version }}/${{ github.event.inputs.version }}.zip'
          # Whether to add subdirectories to simply zip all files to the root
          recursive: true
          
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: 'Release'
          name: 'Release'
          allowUpdates: true
          artifacts: ${{ github.event.inputs.exact_version }}/${{ github.event.inputs.version }}.zip
          bodyFile: 'changelog.md'
          token: ${{ secrets.GITHUB_TOKEN }}

